# Generated by Django 6.1.1 on 2026-09-18 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("menu_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "stock_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "reorder_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "raw_material_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
                ("unit", models.CharField(max_length=20)),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "reorder_threshold",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClosingInventory",
            fields=[
                (
                    "closing_inventory_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("inventory_date", models.DateField()),
                (
                    "expected_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "discrepancy_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.employee",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.menuitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostLayer",
            fields=[
                ("cost_layer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity_remaining",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("received_date", models.DateField(auto_now_add=True)),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.rawmaterial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestockReminder",
            fields=[
                (
                    "restock_reminder_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "quantity_needed",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.rawmaterial",
                    ),
                ),
            ],
        ),
    ]
