# Generated by Django 6.1.1 on 2026-09-19 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterial",
            name="supplier",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="rawmaterial",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="costlayer",
            name="received_date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
    ]
