# Generated by Django 5.2.6 on 2026-09-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rawmaterial_supplier_rawmaterial_unit_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restockreminder",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
