# Generated by Django 6.1.1 on 2026-09-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_restockreminder_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="shelf_life",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
