# Generated by Django 6.1.1 on 2026-09-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_menuitem_category_menuitem_shelf_life"),
    ]

    operations = [
        migrations.AddField(
            model_name="closinginventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("applied", "Applied"),
                    ("dismissed", "Dismissed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
