# Generated by Django 6.1.1 on 2026-09-18 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0001_initial"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionRun",
            fields=[
                ("production_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "planned_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("planned_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="scheduled", max_length=20)),
                (
                    "emp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.employee",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.menuitem",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionConsumption",
            fields=[
                ("consumption_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity_consumed",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.rawmaterial",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.productionrun",
                    ),
                ),
            ],
        ),
    ]
