# Generated by Django 6.1.1 on 2026-09-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_approval_status_recipe_approved_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="approval_status",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="approved_price",
        ),
    ]
