# Generated by Django 6.1.1 on 2026-09-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "calendar_event_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("event_type", models.CharField(max_length=30)),
                ("reference_id", models.IntegerField()),
                ("google_event_id", models.CharField(max_length=255)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
        ),
    ]
