# Generated by Django 6.1.1 on 2026-09-18 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChamsInventory",
            fields=[
                (
                    "chams_inventory_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="BranchLedger",
            fields=[
                (
                    "branch_ledger_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("month", models.DateField()),
                (
                    "beginning_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "restocked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "spoilage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remaining",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "branch_submitted_count",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        db_column="branch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chams.chamsinventory",
                    ),
                ),
            ],
        ),
    ]
